catalogs:
  frontend:
    "@tanstack/query-persist-client-core": "^5.91.4"
    "@tanstack/vue-query": "^5.90.5"
    "aegis-mp-sdk": "^1.39.1"
    "dayjs": "^1.11.19"
    "event-target-polyfill": "^0.0.4"
    "lodash-es": "^4.17.21"
    "urlcat": "^3.1.0"
    "vue": "^3.5.22"
    "vuex": "^4.1.0"
    "vuex-persistedstate": "^4.1.0"
    "yet-another-abortcontroller-polyfill": "^0.0.4"

  infra:
    "@stylistic/eslint-plugin": "^5.5.0"
    "@typescript-eslint/eslint-plugin": "^8.46.2"
    "@typescript-eslint/parser": "^8.46.2"
    "@vue/eslint-config-typescript": "^14.6.0"
    "@zjutjh/eslint-config": "^0.8.0"
    "cspell": "^9.2.2"
    "eslint": "~9.38.0"
    "eslint-config-prettier": "^10.1.8"
    "eslint-import-resolver-typescript": "^4.4.4"
    "eslint-plugin-format": "^1.0.2"
    "eslint-plugin-import": "^2.32.0"
    "eslint-plugin-prettier": "^5.5.4"
    "eslint-plugin-vue": "^10.5.1"
    "globals": "^16.5.0"
    "prettier": "^3.6.2"
    "simple-git-hooks": "^2.13.1"
    "vue-eslint-parser": "^10.2.0"

  taro:
    "@babel/core": "^7.28.5"
    "@babel/runtime": "^7.28.4"
    "@babel/plugin-proposal-class-properties": "7.14.5"
    "@tarojs/components": "4.1.7"
    "@tarojs/cli": "4.1.7"
    "@tarojs/helper": "4.1.7"
    "@tarojs/plugin-framework-vue3": "4.1.7"
    "@tarojs/plugin-platform-weapp": "4.1.7"
    "@tarojs/runtime": "4.1.7"
    "@tarojs/shared": "4.1.7"
    "@tarojs/taro": "4.1.7"
    "@tarojs/vite-runner": "4.1.7"
    "@vitejs/plugin-vue": "^5.2.4"
    "@vitejs/plugin-vue-jsx": "^3.1.0"
    "babel-preset-taro": "4.1.7"
    "postcss": "^8.5.6"
    "sass": "^1.93.3"
    "terser": "^5.44.0"
    "typescript": "^5.9.3"
    "vite": "^4.5.14"

  typing:
    "@types/lodash-es": "^4.17.12"
