export default {
  pages: [
    "pages/index/index",
    "pages/activation/index",
    "pages/bind/index",
    "pages/webview/index",
    "pages/lessonstable/index",
    "pages/schoolbus/index",
    "pages/library/index",
    "pages/schoolcard/index",
    "pages/about/index",
    "pages/exam/index",
    "pages/score/index",
    "pages/setting/index",
    "pages/setting/logout/index",
    "pages/setting/changePassword/index",
    "pages/connect/index",
    "pages/connect/faq/index",
    "pages/lab/index",
    "pages/freeroom/index",
    "pages/announcement/index",
    "pages/electricity/index",
    "pages/electricity/record/index",
    "pages/electricity/consumption/index",
    "pages/electricity/subscribe/index",
    "pages/lostfound/index",
    "pages/information/index",
    "pages/suit/index",
    "pages/suit/faq/index",
    "pages/suit/information/index",
    "pages/suit/apply/index",
    "pages/suit/myapplication/index"
  ],
  darkmode: true,
  themeLocation: "theme.json",
  window: {
    navigationBarBackgroundColor: "@navBgColor",
    navigationBarTextStyle: "@navTxtStyle",
    navigationStyle: "custom",
    backgroundColor: "@bgColor"
  }
};
