on:
  - pull_request

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node_version: 24

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        id: pnpm-install
        with:
          cache: true

      - name: Install dependencies
        run: pnpm ci

      - name: Generate .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Lint changed files
        run: pnpx lint-staged --diff="origin/${{ github.base_ref }}"

      - name: Build Taro weapp
        run: pnpm build:weapp

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: streetsidesoftware/cspell-action@v8
